version: '3.5'

services:

  atomic-angular-demo:
    tty: true
    stdin_open: true
    build:
      context: .
      target: dev
    ports:
      - 4200:4200
    volumes:
      - '.:/usr/src/app'
      - type: volume
        source: nodemodules
        target: /usr/src/app/node_modules
        volume:
          nocopy: true
      - type: volume
        source: npm
        target: /root/.npm
        volume:
          nocopy: true
    labels:
      - "bowtie.project=atomic-angular-demo"
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  npm:
  nodemodules:
